### ISSUE TITLE
依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by rei-01-18** [rei-01-18/protospace-35094#1]
https://protospace-35094.herokuapp.com/user/sign_in

**Comment by Uri-sayaka** [comment]
rei-01-18 さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
◎正しい実装◎
ログイン状態の投稿したユーザーだけに、「編集」「削除」のリンクが存在すること
◎現状◎
ログイン状態の投稿したユーザー以外のユーザーにも「編集」「削除」のリンクが存在しております。


正しい実装へ修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by rei-01-18** [comment]
確認ありがとうございます！
修正しましたので再度確認お願いします

**Comment by Uri-sayaka** [comment]
rei-01-18さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。
